# This is my config for Travis CI
language: node_js

os:
  - linux
  - osx

# Versions of Node to support
node_js:
  - "8"
  - "lts/*"
  - "node"

install:
  - npm install

before_script:
  - npm run build

script:
  - npm test

